export const mockedState = {
  todos: [{
      title: "Monaco - What do you want from me?",
      items: [{
          id: 1,
          title: 'There\'s one thing I would die for',
          dueTo: null,
          done: true,
        },
        {
          id: 2,
          title: 'It\'s  when you say my life is in your hands',
          dueTo: null,
          done: false,
        },
        {
          id: 3,
          title: '\'cause when you\'re near me your love is all I need',
          dueTo: null,
          done: true,
        },
        {
          id: 4,
          title: 'Now I can\'t imagine',
          dueTo: null,
          done: false,
        },
        {
          id: 5,
          title: 'What do you want from me?',
          dueTo: null,
          done: false,
        },
        {
          id: 6,
          title: 'It\'s not how it used to be',
          dueTo: null,
          done: false,
        },
        {
          id: 7,
          title: 'You\'ve taken my life away',
          dueTo: null,
          done: false,
        },
        {
          id: 8,
          title: 'Ruining everything',
          dueTo: null,
          done: false,
        },
        {
          id: 9,
          title: 'Sha la la la la la la',
          dueTo: null,
          done: false,
        },
        {
          id: 10,
          title: 'Sha la la la la la la',
          dueTo: null,
          done: false,
        },
        {
          id: 11,
          title: 'Sha la la la la la la',
          dueTo: null,
          done: false,
        },
        {
          id: 12,
          title: 'Sha la la la la la la',
          dueTo: null,
          done: false,
        },
      ],
    },
    {
      title: "Peter Gabriel - Mercy Street",
      items: [{
          id: 1,
          title: 'Looking down an empty street all she can see',
          dueTo: null,
          done: true,
        },
        {
          id: 2,
          title: 'Are the dreams all made solid, are the dreams made real',
          dueTo: null,
          done: false,
        },
        {
          id: 3,
          title: 'All of the buildings, all of the cars',
          dueTo: null,
          done: true,
        },
        {
          id: 4,
          title: 'Were once just a dream in somebodys head',
          dueTo: null,
          done: false,
        },
        {
          id: 5,
          title: 'She pictureas a broken glass she pictures the steam',
          dueTo: null,
          done: false,
        },
        {
          id: 6,
          title: 'She pictures a soul with no leak at the seam',
          dueTo: null,
          done: false,
        },
        {
          id: 7,
          title: 'Let\'s take the boat out wait until darknes comes',
          dueTo: null,
          done: false,
        },
        {
          id: 8,
          title: ' Nowhere in ther corridor of pale green and gray',
          dueTo: null,
          done: false,
        },
        {
          id: 9,
          title: 'Nowhere in the suburbs in the cold light of day',
          dueTo: null,
          done: false,
        },
        {
          id: 10,
          title: 'There in the mildst of this so alive and alone',
          dueTo: null,
          done: false,
        },
        {
          id: 11,
          title: 'Words supports like bones',
          dueTo: null,
          done: false,
        },
        {
          id: 12,
          title: 'Dreaming of Mercy Street',
          dueTo: null,
          done: false,
        },
        {
          id: 13,
          title: 'When you\'re inside out',
          dueTo: null,
          done: false,
        },
        {
          id: 14,
          title: 'Dreaming of Mercy',
          dueTo: null,
          done: false,
        },
        {
          id: 15,
          title: 'In your daddy\'s arms again',
          dueTo: null,
          done: false,
        },
      ],
    },
    {
      title: "Mundo Bita - Fazendinha",
      items: [{
          id: 1,
          title: 'Bom dia! O sol já nasceu lá na Fazendinha',
          dueTo: null,
          done: true,
        },
        {
          id: 2,
          title: 'Acorda o bezerro e a vaquinha',
          dueTo: null,
          done: false,
        },
        {
          id: 3,
          title: 'Que já cocoricou dona galinha',
          dueTo: null,
          done: true,
        },
        {
          id: 4,
          title: 'Levanta! O cavalinho já pulou da cama',
          dueTo: null,
          done: false,
        },
        {
          id: 5,
          title: 'E o pintinho tirou seu pijama',
          dueTo: null,
          done: false,
        },
        {
          id: 6,
          title: 'E o porquinho já caiu na lama',
          dueTo: null,
          done: false,
        },
      ],
    },
  ],
};